version: "3"
services:
  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot
    image: spring-boot-project-1
    depends_on:
      - mysqldb
    restart: always
    ports:
      - 8080:8080
    networks:
      - spring-mysql
    environment:
      JAR_FILE: "salah.jar"
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/mini_project_1",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.show-sql":"true"
          }'

  mysqldb:
    image: mysql:8
    platform: linux/x86_64
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - spring-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3307:3306

networks:
  spring-mysql:
